### ISSUE TITLE
FileInputStream / FileOutputStream Considered Harmful

### ISSUE THREAD

**Issue by nclemeur** [vy/rotating-fos#174]
Hello,

I just came accross this article: 

https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful

I am wondering if this could be applied/improved to rotating-fos?

**Comment by vy** [comment]
@nclemeur, as the one of the very first sentences of the `README.md` states: _"`RotatingFileOutputStream` does not extend `java.io.FileOutputStream`"_ Hence, we are already covered. :sunglasses:

Nevertheless, I did not know of the problem you shared. Thanks for raising it. I will share it in the `README.md` to add to our reasoning of not extending from FOS.

**Comment by vy** [comment]
Sorry, I am still trying to wake up. We indeed don't extend from `FOS`, but use it. Would you like to submit a PR?

**Comment by vy** [comment]
@nclemeur, thanks so much!
1. Added you to the list of contributors
2. Updated the changelog
3. Released `0.9.6`
