### ISSUE TITLE
Same trigger instant may be calculated, resulting in loss of logs

### ISSUE THREAD

**Issue by broafka-ottokar** [vy/rotating-fos#207]
The following line:
https://github.com/vy/rotating-fos/blob/24b90e074add13cc6b641ec18587bfc705be26ae/src/main/java/com/vlkan/rfos/policy/TimeBasedRotationPolicy.java#L63
rounds the delay **down** to the nearest millis, causing the rotation to happen <1 ms too soon. After the rotation, 
https://github.com/vy/rotating-fos/blob/24b90e074add13cc6b641ec18587bfc705be26ae/src/main/java/com/vlkan/rfos/policy/TimeBasedRotationPolicy.java#L62
may calculate the same triggerInstant (because we are still ahead the previous one), causing filename duplication and overwritten files. These **will** happen on a properly fast machine.

Solution: add 1 ms to the delay or round up.

**Comment by vy** [comment]
@broafka-ottokar, thanks so much for the report. I will see what I can do about it.

In the meantime, curious: In which application do you use `rotating-fos`? What is your use case?

**Comment by vy** [comment]
@broafka-ottokar, 19a033ea8f9399af0a54f2b8f8d2086a26564048 fixes the issue in two angles:

1. Switched to nanosecond resolution while scheduling the triggering task
2. Ensuring `triggerInstant > lastTriggerInstant`

Could you review the fix, please? If you are also okay, I will do a patch release.

**Comment by vy** [comment]
@broafka-ottokar, released `0.9.7`. It should be available on Maven Central momentarily.
