### ISSUE TITLE
Add line-based rotation

### ISSUE THREAD

**Issue by alturkovic** [vy/rotating-fos#222]
Would it be possible to provide more information to policies about the current written file except the `byteCount`?

I have a use-case where I need to rotate a file based on 2 conditions: each file should have at most n lines (each line is a json) and it should be rotated each m minutes. I am sure I can figure out how to make a `CompositeRotationPolicy`, but I am not sure how I could tackle the line issue. Is this something that would be possible with your library or do you have other suggestions?

**Comment by alturkovic** [comment]
Thanks for the quick reply! 
This seems to work well enough, I just noticed a slight problem. If the application using this library is restarted, the line count would not be accurate since this implementation assumes that the initial line count is zero, but it does not have to be. Maybe the initial line count could be extracted from the "last" rotation when initialized?

**Comment by vy** [comment]
@alturkovic, I have pushed a fix in 838ced6ec6caad91b82eee52d67be6cc921865ce. Can you review again, please?

**Comment by alturkovic** [comment]
Is there any reason why you decided to use `\n` for line separators instead of `System.lineSeparator()`? 

That is the only thing I noticed that might introduce unexpected problems depending on the system using this library, but other than that, everything seems good to me 😄

Thank you for your help!

**Comment by alturkovic** [comment]
Isn't `\r\n` officialy the line separator on Windows? Counting only `\n` on Windows might not be accurate if I am not mistaken.

**Comment by alturkovic** [comment]
See also: https://stackoverflow.com/questions/426397/do-line-endings-differ-between-windows-and-linux

**Comment by vy** [comment]
I am aware of CRLF-vs-LF difference between platforms. Indeed counting only `\n` on Windows _might_ not be accurate. But I doubt if this drawback is important enough to bite the bullet and implement a multi-char matcher, which is significantly more complicated. I will see if I can get this _efficiently_ done.

**Comment by alturkovic** [comment]
Understandable, and to be fair, I don't think this would actually cause any problems in practice, and if the solution is more complicated than what I initially thought (just using `System.lineSeparator()`), I do not think it is worth the additional effort.

Thank you for your time on this task.

**Comment by vy** [comment]
Fixed in #223 and released with `0.10.0`.
