### ISSUE TITLE
SizeBasedRotationPolicy not rotating as expected

### ISSUE THREAD

**Issue by pitschr** [vy/rotating-fos#4]
Hello.

Not sure if it is a bug, but it seems `SizeBasedRotationPolicy` is not working (at least for me)

Given minimal JUnit test:
* I am writing a lot of "Hello World!" into the file
* The size is limited to 1kb (=1024 bytes)
* The check interval is set as 0 to ensure that it is not write sensitive

``` 
import com.vlkan.rfos.RotatingFileOutputStream;
import com.vlkan.rfos.RotationConfig;
import com.vlkan.rfos.policy.DailyRotationPolicy;
import com.vlkan.rfos.policy.SizeBasedRotationPolicy;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class TestRotation {
    @Test
    public void test() {
        final var config = RotationConfig
                .builder()
                .file("C:/Temp/app.log")
                .filePattern("C:/Temp/app-%d{yyyyMMdd-HHmmss-SSS}.log")
                .policy(new SizeBasedRotationPolicy(0, 1024  /* 1 kb */))
                .build();

        try (var fos = new RotatingFileOutputStream(config)) {
            final var bytes = "Hello World!Hello World!Hello World! Hello World!Hello World! Hello World!Hello World! Hello World!".getBytes(StandardCharsets.UTF_8);
            for (int i=0; i<100; i++) {
                fos.write(bytes);
                Thread.sleep(10);
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
``` 

The first run creates a 10kB file. The second run will append more 10kB. After third run the file is 30kB big. Perhaps my understanding of rotation is wrong? Can you elaborate how I can rotate the file based on the file size?

Thank you, Chris

**Comment by pitschr** [comment]
p.s. I am using version 0.7 (downloaded and trying out the library for first time)

**Comment by pitschr** [comment]
Additional info: 

It seems the issue is somewhere with non write sensitive functionality.

When using:
`.policy(new SizeBasedRotationPolicy(1, 1024  /* 1 kb */))` 

then the rotation policy is working as expected. The issue is only that the file may become 10kB when we write more than 1kB in 1 milliseconds.

I suggest to either fix the issue for long-term. As short-term I suggest to add check that `checkIntervallMillis` must be larger than zero. In same way how it was done for version 0.4 where I could not reproduce the issue.

Hope that helps!

**Comment by vy** [comment]
Hey @pitschr! Thanks for using the library and feedback. I am having a difficulty in reproducing the problem you encountered. I have translated the Java snippet you shared into Java 8 and placed it under the `test/com/vlkan/rfos/RotationTest.java` of the `master` branch:

```java
package com.vlkan.rfos;

import com.vlkan.rfos.policy.RotationPolicy;
import com.vlkan.rfos.policy.SizeBasedRotationPolicy;
import org.junit.Test;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.time.Instant;

public class RotationTest {

    @Test
    public void test() throws Exception {
        RotationConfig config = RotationConfig
                .builder()
                .file("/tmp/app.log")
                .filePattern("/tmp/app-%d{yyyyMMdd-HHmmss-SSS}.log")
                .policy(new SizeBasedRotationPolicy(0, 1024  /* 1 kb */))
                .callback(new RotationCallback() {

                    @Override
                    public void onTrigger(RotationPolicy policy, Instant instant) {
                        System.out.format("onTrigger(%s, %s)%n", policy, instant);
                    }

                    @Override
                    public void onSuccess(RotationPolicy policy, Instant instant, File file) {
                        System.out.format("onSuccess(%s, %s, %s)%n", policy, instant, file);

                    }

                    @Override
                    public void onFailure(RotationPolicy policy, Instant instant, File file, Exception error) {
                        System.out.format("onFailure(%s, %s, %s)%n", policy, instant, file);
                        error.printStackTrace();
                    }

                })
                .build();

        try (RotatingFileOutputStream fos = new RotatingFileOutputStream(config)) {
            byte[] bytes = ("Hello World!" +
                    "Hello World!" +
                    "Hello World!" +
                    "Hello World!" +
                    "Hello World!" +
                    "Hello World!" +
                    "Hello World!" +
                    "Hello World!").getBytes(StandardCharsets.UTF_8);
            for (int i=0; i<100; i++) {
                fos.write(bytes);
                Thread.sleep(10);
            }
        }
    }

}
```

I've run the `@Test` method twice. In the first run, I got the following output:

```
$ ls -alh /tmp/app*
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-517.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-648.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-753.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-858.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-961.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-066.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-171.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-277.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-382.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app.log
```

In the second run I get this:

```
$ ls -alh /tmp/app*
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-517.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-648.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-753.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-858.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131108-961.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-066.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-171.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-277.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131109-382.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:11 /tmp/app-20191105-131533-525.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131533-643.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131533-747.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131533-849.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131533-952.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131534-054.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131534-157.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131534-262.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131534-368.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app-20191105-131534-472.log
-rw-rw-r-- 1 vy vy 990 Nov  5 13:15 /tmp/app.log
```

I am puzzled by what do you mean by

> The first run creates a 10kB file. The second run will append more 10kB. After third run the file is 30kB big.

**Comment by pitschr** [comment]
> The first run creates a 10kB file. The second run will append more 10kB. After third run the file is 30kB big.

In my case the app.log was increased to 10kb after first JUnit test run. When I re-execute the JUnit test then app.log was increased from 10kB to 20kB ... and so on ...

Given your result you are using either a Mac or Linux. Perhaps the result is different on Windows as, when executing your test, I am getting:
```
onFailure(SizeBasedRotationPolicy{checkIntervalMillis=0, maxByteCount=1024}, 2019-11-05T13:23:24.844739900Z, C:\tmp\app-20191105-132324-844.log)
java.io.IOException: rename failure {file=\tmp\app.log, rotatedFile=C:\tmp\app-20191105-132324-844.log}
	at com.vlkan.rfos.RotatingFileOutputStream.unsafeRotate(RotatingFileOutputStream.java:87)
	at com.vlkan.rfos.RotatingFileOutputStream.rotate(RotatingFileOutputStream.java:62)
	at com.vlkan.rfos.policy.SizeBasedRotationPolicy.rotate(SizeBasedRotationPolicy.java:101)
	at com.vlkan.rfos.policy.SizeBasedRotationPolicy.acceptWrite(SizeBasedRotationPolicy.java:57)
	at com.vlkan.rfos.RotatingFileOutputStream.notifyWriteSensitivePolicies(RotatingFileOutputStream.java:198)
	at com.vlkan.rfos.RotatingFileOutputStream.write(RotatingFileOutputStream.java:183)
	at com.vlkan.rfos.RotationTest.test(RotationTest.java:52)
	... lines omitted ...
```

In my case it creates a `app.log` file in C:\tmp folder ( C:\tmp\app.log ), but the rename fails for some reasons and the error occurs in WinNTFFileSystem that is calling a native method. So it is clear, why the issue is not reproducible by you. You're lucky! :-D

Based on my experience filesystem issues like that happens when the stream is not closed properly. After digging the code I see that old stream is closed AFTER the rename action. On unix-like environments the files remain open (as you can see in `lsof` command) which also gives more flexibility. Windows is more restrictive, I am afraid, but at least this is the explanation.

I checked our project and fixed the root cause. It is working on Windows machine. I would like to ask to review the PR and check if the RotationTest and all your tests are also successful on unix-like machines.

Pull Request: https://github.com/vy/rotating-fos/pull/5

If everything is OK from your side I would like to ask you to provide the next version on maven repository so that I can re-use the library from the origin project source.

Thank you for providing the library as well - it is really helpful!

**Comment by vy** [comment]
@pitschr, it took quite some effort to

1. Introduce a Windows pipeline into CI to let the failure surface.
2. Get your changes in.

Thanks so much! I've added your name "Christoph (pitschr) Pitschmann" to the list of contributors. (Let me know if you are not okay with that.)

Would you mind verifying the fix also works on your machine? If so, I will make a new release sometime tomorrow.

**Comment by pitschr** [comment]
Hello. Thank you for your effort. I have tested on my machine (Windows) and can confirm that your tests are successful and I am not able to reproduce the issue I reported anymore.

Thank you for adding me as contributor - I'm fine with it :-) 

Have a nice day!

**Comment by vy** [comment]
v0.8 is on Maven Central, enjoy!
