### ISSUE TITLE
File rotation not working 

### ISSUE THREAD

**Issue by paulisev** [vy/rotating-fos#49]
File rotation is not working as documented.  File rotation will only create 2 back up files (file.0 and file.maxBackup-1) irrespective of the value of maxBackup. For example if you set maxBackup=5; file rotation will only create two back up files file.0 and file.4.
Need to add `dstFile = srcFile;` before `continue` 
(https://github.com/vy/rotating-fos/blob/master/src/main/java/com/vlkan/rfos/RotatingFileOutputStream.java#L179)

**Comment by vy** [comment]
@paulisev, mind submitting a PR first reproducing the issue in `RotatingFileOutputStreamTest#test_maxBackupCount()` and fixing it, please?

**Comment by vy** [comment]
Fixed in 0.9.4! :tada:
