### ISSUE TITLE
IOException is not propagated

### ISSUE THREAD

**Issue by chavolla** [vy/rotating-fos#86]
https://github.com/vy/rotating-fos/blob/8967d56081b36a611089ab097114ed303e9cd441/src/main/java/com/vlkan/rfos/RotatingFileOutputStream.java#L110-L113

If an error happens while opening the file the IOException is ignored just a generic Runtime Exception is thrown. The original exception should be added as the inner cause for the Runtime Exception.
```
 throw new RuntimeException(message, error);
```
or at least log the IOException

**Comment by vy** [comment]
@chavolla, thanks so much for the heads up. I've fixed the issue and released 0.9.5.
