### ISSUE TITLE
Release v0.9.5 not found on maven central repository

### ISSUE THREAD

**Issue by itatdcer** [vy/rotating-fos#91]
## Description
When I try to use the latest release (v0.9.5) in my pom, I get the error 
`Could not find artifact com.vlkan.rfos:rotating-fos:jar:0.9.5 in central (https://repo.maven.apache.org/maven2)`

**Comment by vy** [comment]
@itatdcer Doh! :man_facepalming: Apparently something went wrong while I was trying to promote the release in the Nexus. Thanks so much for the heads up! :bow: Here you go, [0.9.5](https://repo1.maven.org/maven2/com/vlkan/rfos/rotating-fos/0.9.5/)! :tada:
